// Writes app/library/compose-table.ts: base letter + one combining mark →
// the precomposed letter, for every letter in Latin-1 Supplement and Latin
// Extended-A (U+00C0–017F) that canonically decomposes that way. Generated
// with the build machine's String.prototype.normalize so the 3DS needs none.
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const entries: string[] = [];
for (let cp = 0xc0; cp <= 0x17f; cp++) {
  const ch = String.fromCodePoint(cp);
  const parts = [...ch.normalize("NFD")];
  if (parts.length === 2 && /[̀-ͯ]/.test(parts[1]!)) {
    const key = parts[0]! + "\\u" + parts[1]!.codePointAt(0)!.toString(16).padStart(4, "0");
    entries.push(`  "${key}": "${ch}",`);
  }
}
const out = [
  "// Generated by scripts/gen-compose-table.ts — do not edit.",
  "// Base letter + combining mark → precomposed Latin-1 / Latin Extended-A letter.",
  "export const COMPOSE: Readonly<Record<string, string>> = {",
  ...entries,
  "};",
  "",
].join("\n");
writeFileSync(join(import.meta.dir, "..", "app", "library", "compose-table.ts"), out);
console.log(`${entries.length} compositions`);
