// The cover-loading spinner: a Mac OS X-era 12-spoke grey spinner as a
// 4x4 sprite atlas of 32 px cells (16 frames), baked by the build from
// app/theme/icons/spinner-atlas.svg and declared in app/sprites.json. The SVG
// baker scans shapes flat (no transforms), so every spoke is a capsule path
// with its frame's offset already applied. The core needs power-of-two atlas
// sides that divide into the frame grid, which 12 frames cannot do, so the
// lead spoke advances 3/4 of a spoke per frame with its brightness shared
// between neighbouring spokes.
//
//   bun scripts/spinner-atlas.ts      (rewrites the committed SVG)
import { writeFileSync } from "node:fs";
import { join } from "node:path";

/** Atlas layout and timing; 16 frames of 4 core ticks (60 Hz) turn it about once a second. */
export const SPINNER = { cell: 32, cols: 4, rows: 4, frames: 16, step: 4 } as const;

const SPOKES = 12;
const INNER = 7;
const OUTER = 14;
const HALF_WIDTH = 1.7;
const INK = "#5a5a5a";
/** Opacity by how many spokes a spoke trails the lead one. */
const TRAIL = [1, 0.86, 0.73, 0.62, 0.52, 0.44, 0.37, 0.31, 0.26, 0.22, 0.19, 0.16];

/** Opacity of a spoke `trail` spokes behind the lead (fractional: blended between steps). */
function trailOpacity(trail: number): number {
  const lower = Math.floor(trail) % SPOKES, upper = (lower + 1) % SPOKES, t = trail - Math.floor(trail);
  return Math.round((TRAIL[lower]! * (1 - t) + TRAIL[upper]! * t) * 100) / 100;
}

const fixed = (n: number) => (Math.abs(n) < 0.005 ? 0 : n).toFixed(2);

function spoke(cx: number, cy: number, index: number, opacity: number): string {
  const angle = (index * 2 * Math.PI) / SPOKES; // 0 at twelve o'clock, clockwise
  const dx = Math.sin(angle), dy = -Math.cos(angle);
  const nx = -dy * HALF_WIDTH, ny = dx * HALF_WIDTH;
  const ax = cx + dx * INNER, ay = cy + dy * INNER;
  const bx = cx + dx * OUTER, by = cy + dy * OUTER;
  // Round ends as two cubic quarter circles each (the baker has no arc command).
  const k = 0.5523;
  const ux = dx * HALF_WIDTH, uy = dy * HALF_WIDTH;
  const P = (x: number, y: number) => `${fixed(x)} ${fixed(y)}`;
  /** From p + m round the end at p + s to p - m. */
  const cap = (px: number, py: number, mx: number, my: number, sx: number, sy: number) =>
    `C${P(px + mx + sx * k, py + my + sy * k)} ${P(px + sx + mx * k, py + sy + my * k)} ${P(px + sx, py + sy)}` +
    `C${P(px + sx - mx * k, py + sy - my * k)} ${P(px - mx + sx * k, py - my + sy * k)} ${P(px - mx, py - my)}`;
  const d = `M${P(ax + nx, ay + ny)}L${P(bx + nx, by + ny)}${cap(bx, by, nx, ny, ux, uy)}` +
    `L${P(ax - nx, ay - ny)}${cap(ax, ay, -nx, -ny, -ux, -uy)}Z`;
  return `  <path d="${d}" fill="${INK}" opacity="${opacity}" />`;
}

export function spinnerAtlasSvg(): string {
  const { cell, cols, rows, frames } = SPINNER;
  const lines = [
    `<!-- Generated by scripts/spinner-atlas.ts: ${frames} frames of a ${SPOKES}-spoke spinner, ${cols}x${rows} cells of ${cell} px. -->`,
    `<svg xmlns="http://www.w3.org/2000/svg" width="${cols * cell}" height="${rows * cell}" viewBox="0 0 ${cols * cell} ${rows * cell}">`,
  ];
  for (let frame = 0; frame < frames; frame++) {
    const cx = (frame % cols) * cell + cell / 2, cy = Math.floor(frame / cols) * cell + cell / 2;
    const lead = (frame * SPOKES) / frames;
    for (let index = 0; index < SPOKES; index++) {
      lines.push(spoke(cx, cy, index, trailOpacity((lead - index + SPOKES) % SPOKES)));
    }
  }
  lines.push("</svg>", "");
  return lines.join("\n");
}

if (import.meta.main) {
  const out = join(import.meta.dir, "../app/theme/icons/spinner-atlas.svg");
  writeFileSync(out, spinnerAtlasSvg());
  console.log(`spinner-atlas: wrote ${out}`);
}
