// The test library's output folder: the generator clears only a folder it made
// itself (marked by LIBRARY_MARKER) or an empty one, never a folder of real music.
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const LIBRARY_MARKER = ".ds-man-test-library";

/** Leaves `dir` empty except for the marker; throws for a folder holding files this script did not write. */
export function prepareLibraryDir(dir: string): void {
  if (existsSync(dir)) {
    const entries = readdirSync(dir);
    if (entries.length > 0 && !entries.includes(LIBRARY_MARKER)) {
      throw new Error(`make-test-library: ${dir} holds files this script did not write; pick an empty or new folder`);
    }
    rmSync(dir, { recursive: true, force: true });
  }
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, LIBRARY_MARKER), "Generated by scripts/make-test-library.ts; safe to delete.\n");
}
